[DeviceProfiles]
+DeviceProfileNameAndTypes=Content_SM5,Android

[/Script/AndroidDeviceProfileSelector.AndroidDeviceProfileMatchingRules]
+MatchProfile=(Profile="Content_SM5",Match=((SourceType=SRC_GpuFamily,CompareType=CMP_Regex,MatchString="Mali"),(SourceType=SRC_AndroidVersion, CompareType=CMP_Regex,MatchString="([0-9]+).*"),(SourceType=SRC_PreviousRegexMatch,CompareType=CMP_GreaterEqual,MatchString="10"),(SourceType=SRC_VulkanAvailable,CompareType=CMP_Equal,MatchString="true")))

[Content_SM5 DeviceProfile]
DeviceType=Android
BaseProfileName=Android
;BaseProfileName=Android_Vulkan_SM5

; Use R11G11B10_Float format for HDR scene color
+CVars=r.SceneColorFormat=2
+CVars=r.Mobile.SceneColorFormat=2

; For UE5.4, workaround for DDK bug, https://jira.arm.com/browse/GRAPHICSSW-47450 
+CVars=a.UseSwappyForFramePacing=0 

; Disable rough diffuse for saving lighting cost(0)
;+CVars=r.Substrate.RoughDiffuse=0
; Reduce shading quality for performance(0)
;+CVars=r.Substrate.ShadingQuality=2
+CVars=r.Substrate.TileCoord8bits=1

; Ray tracing related variables ------------------------------------------------------------------
+CVars=r.RayTracing.AllowInline=True
+CVars=r.RayTracing.AllowPipeline=False
; For 5.4 only
+CVars=r.RayTracing.RequireSM6=0 
; For software Lumen
+CVars=r.DistanceFields=1
+CVars=r.DistanceFields.SupportEvenIfHardwareRayTracingSupported=1

; Vulkan related variables ------------------------------------------------------------------
; Enable Vulkan SM5 support
+CVars=r.Android.DisableVulkanSM5Support=0
+CVars=r.Android.DisableVulkanSupport=0
; Avoid using VK_IMAGE_USAGE_STORAGE_BIT which will disable AFBC
+CVars=r.Vulkan.DepthStencilForceStorageBit=0
+CVars=r.Vulkan.RayTracing.AllowCompaction=0
; TLAS building prefer fast build as fast trace building is slow
+CVars=r.Vulkan.RayTracing.TLASPreferFastTraceTLAS=False

; Lumen related variables ------------------------------------------------------------------
; Avoid using FORCE_NON_OPAQUE flag in ray query shader
+CVars=r.Lumen.HardwareRayTracing.SkipBackFaceHitDistance=-100.0
+CVars=r.Lumen.HardwareRayTracing.SkipTwoSidedHitDistance=-100.0

;+CVars=r.Lumen.DiffuseIndirect.Allow=1
;+CVars=r.Lumen.TraceMeshSDFs.Allow=1

;+CVars=r.Lumen.HardwareRayTracing.MaxIterations=1024

+CVars=r.LumenScene.DirectLighting.UpdateFactor=32
+CVars=r.LumenScene.Radiosity.UpdateFactor=64
;+CVars=r.LumenScene.Radiosity.ProbeSpacing=16
;+CVars=r.LumenScene.Radiosity.HemisphereProbeResolution=3

;+CVars=r.Lumen.ScreenProbeGather.RadianceCache.ProbeResolution=16
;+CVars=r.Lumen.ScreenProbeGather.RadianceCache.NumProbesToTraceBudget=240
;+CVars=r.Lumen.ScreenProbeGather.DownsampleFactor=32
;+CVars=r.Lumen.ScreenProbeGather.TracingOctahedronResolution=6
;+CVars=r.Lumen.ScreenProbeGather.IrradianceFormat=1
;+CVars=r.Lumen.ScreenProbeGather.StochasticInterpolation=1
;+CVars=r.Lumen.ScreenProbeGather.FullResolutionJitterWidth=1
;+CVars=r.Lumen.ScreenProbeGather.TwoSidedFoliageBackfaceDiffuse=0
;+CVars=r.Lumen.ScreenProbeGather.ScreenTraces.HZBTraversal.FullResDepth=0
+CVars=r.Lumen.ScreenProbeGather.ShortRangeAO=1

+CVars=r.Lumen.Reflections.RadianceCache=1
;+CVars=r.Lumen.Reflections.DownsampleFactor=4
+CVars=r.Lumen.Reflections.MaxRoughnessToTrace=0.4
;+CVars=r.Lumen.Reflections.MaxRoughnessToTraceForFoliage=0.2
;+CVars=r.Lumen.TranslucencyReflections.FrontLayer.Allow=0
;+CVars=r.Lumen.TranslucencyReflections.FrontLayer.Enable=0

+CVars=r.Lumen.TranslucencyVolume.Enable=0
;+CVars=r.Lumen.TranslucencyVolume.GridPixelSize=64
;+CVars=r.Lumen.TranslucencyVolume.TraceFromVolume=0
;+CVars=r.Lumen.TranslucencyVolume.RadianceCache.ProbeResolution=8
;+CVars=r.Lumen.TranslucencyVolume.RadianceCache.NumProbesToTraceBudget=200




;+CVars=sg.ResolutionQuality=80
;+CVars=sg.ViewDistanceQuality=2
;+CVars=sg.AntiAliasingQuality=3
;+CVars=sg.ShadowQuality=3
;+CVars=sg.PostProcessQuality=3
;+CVars=sg.TextureQuality=3
;+CVars=sg.EffectsQuality=3
;+CVars=sg.FoliageQuality=0
;+CVars=sg.ShadingQuality=3
;+CVars=r.BloomQuality=5
;+CVars=r.LightShaftQuality=0
; Shadows
;+CVars=r.Shadow.MaxResolution=1024
;+CVars=r.Shadow.MaxCSMResolution=1024
;+CVars=r.Shadow.WholeSceneShadowCacheMb=40
; This will disable/enable spot light shadow
+CVars=r.Shadow.CachedShadowsCastFromMovablePrimitives=1
+CVars=r.Shadow.MaxNumPointShadowCacheUpdatesPerFrame=0
+CVars=r.Shadow.MaxNumSpotShadowCacheUpdatesPerFrame=3
;+CVars=r.Shadow.DistanceScale=1.0
;+CVars=r.Shadow.CSM.MaxCascades=3
;+CVars=r.ShadowQuality=3
+CVars=r.Shadow.CSMShadowDistanceFadeoutMultiplier=2.5
;+CVars=r.SSS.Quality=0
;+CVars=r.SSS.Scale=0
;+CVars=r.SSR.Quality=2
;+CVars=r.VirtualTextures=0




;DOF
;+CVars=r.DepthOfFieldQuality=3
;+CVars=r.DOF.Gather.AccumulatorQuality=1        ; higher gathering accumulator quality
;+CVars=r.DOF.Gather.PostfilterMethod=1          ; Median3x3 postfilering method
;+CVars=r.DOF.Gather.EnableBokehSettings=1       ; bokeh simulation when gathering
;+CVars=r.DOF.Gather.RingCount=5                 ; high number of samples when gathering
;+CVars=r.DOF.Scatter.ForegroundCompositing=1    ; additive foreground scattering
;+CVars=r.DOF.Scatter.BackgroundCompositing=2    ; background scattering occlusion
;+CVars=r.DOF.Scatter.EnableBokehSettings=1      ; no bokeh simulation when scattering
;+CVars=r.DOF.Scatter.MaxSpriteRatio=0.25        ; only a maximum of 10% of scattered bokeh
;+CVars=r.DOF.Recombine.Quality=2                ; highest slight out of focus
;+CVars=r.DOF.Recombine.EnableBokehSettings=1    ; bokeh simulation on slight out of focus
;+CVars=r.DOF.TemporalAAQuality=1                ; more stable temporal accumulation
;+CVars=r.DOF.Kernel.MaxForegroundRadius=0.025
;+CVars=r.DOF.Kernel.MaxBackgroundRadius=0.025

; TAA
;+CVars=r.TemporalAA.Upsampling=True
;+CVars=r.TemporalAA.Quality=1

; FXAA
;+CVars=r.FXAA.Quality=5

; HDR output
;+CVars=r.AllowHDR=True
;+CVars=r.HDR.EnableHDROutput=True
;+CVars=r.HDR.Display.OutputDevice=0

;Lumen setting


;+CVars=r.DistanceFieldAO=0
;+CVars=r.AOQuality=1

[Android_Mali_G78_Vulkan DeviceProfile]
DeviceType=Android
BaseProfileName=Content_SM5

[Android_Mali_G710_Vulkan DeviceProfile]
DeviceType=Android
BaseProfileName=Content_SM5

[Android_Mali_G7xx_Vulkan DeviceProfile]
DeviceType=Android
BaseProfileName=Content_SM5

[Android_Mali_G9xx_Vulkan DeviceProfile]
DeviceType=Android
BaseProfileName=Content_SM5

[Android_Mali_Vulkan_SM5 DeviceProfile]
DeviceType=Android
BaseProfileName=Content_SM5

[Android_Unknown_Vulkan DeviceProfile]
DeviceType=Android
BaseProfileName=Content_SM5

[Android_Adreno7xx_Vulkan DeviceProfile]
DeviceType=Android
BaseProfileName=Content_SM5

[Android_Adreno8xx_Vulkan DeviceProfile]
DeviceType=Android
BaseProfileName=Content_SM5

[Android_Mali_TDRX DeviceProfile]
DeviceType=Android
BaseProfileName=Content_SM5

